### ISSUE TITLE
Anmeldung erforderlich, obwohl angemeldet

### ISSUE THREAD

**Issue by rombau** [rombau/osext2#15]
Wenn sich ein Spieler des Demoteam auf der Beobachtungsliste befindet, kommt es zum Fehler "Anmeldung erforderlich"

**Comment by Eselce** [comment]
Merknotiz für die Identifikation der entsprechenden Zeile:
```
document.querySelector('div#a table tr td table tr td[align=center] b').innerHTML
"Willkommen im Managerbüro von Choromonets Odessa"
```
extrahiert die zentrierte fette Tabellenspalte. Kürzer aber unpräziser:
`document.querySelector('td[ALIGN=center] b').textContent`

**Comment by rombau** [comment]
Behoben mit https://github.com/rombau/osext2/commit/2d64d111063404e87022b9f2c782af7b7152769b
