### ISSUE TITLE
Ungenaue bzw. unnötige reguläre Ausdrücke (Match Patterns)

### ISSUE THREAD

**Issue by Eselce** [rombau/osext2#16]
Mir sind ein paar verbesserungsfähige Patterns aufgefallen, insbesondere die `.+` für Umlaute, die zu ungeahnten Folgen führen könnten.
Zudem braucht es für die Entfernung der Punkte in Zahlen kein Pattern, hier genügt ein `replaceAll` mit dem einfachen Zeichen.
Ein richtiger Fehler ist das Nichterkennen von `2. Liga A Deutschland` als `2. Liga` von `Deutschland`.

**Comment by rombau** [comment]
Die Umlaut-Suche in den Regex Patterns und das Entfernen der Punkte in Zahlen werde ich mir anschauen.

Der Name des Landes wird tatsächlich nicht richtig ausgelesen:
`/(\d)\. Liga (.+)/`
bei 2. Liga A Deutschland
- match 1 (league.level) = `2` 
- match 1 (league.countryName) = `A Deutschland`
ist zwar aktuell nicht tragisch, weil nicht verwendet, aber schau ich mir auch an.

**Comment by Eselce** [comment]
Das hatte ich natürlich nachgeschaut, daß nur der `league.level` interessierte.
Das Land wird einfach nur falsch rausgezogen. Tragisch ist das nicht, nur falsch.

Ansonsten siehe Pull Request, den ich leider nicht pushen konnte (siehe Discord).
