### ISSUE TITLE
Synchronisierte Ladevorgänge können sich aufhängen

### ISSUE THREAD

**Issue by Eselce** [rombau/osext2#24]
Da ich den konkreten Fall nicht gut reproduziert bekomme, dann eben das übergeordnete Thema.
Es ist bereits bei den Anmeldeproblemen vorgekommen, kann aber immer noch passieren.

Wenn die `operation` sich aufhängt, geht's einfach nicht weiter, keine weitere Operation kann ausgeführt werden.
Vermutlich (dies wäre zu prüfen) wird das Ganze sogar im Hauptthread ausgeführt, was den Browser blockiert.

Verschiedene Ansätze sind hier möglich, z.B. Time-Out oder Abbruch bei Klick auf die Meldung...

**Comment by Eselce** [comment]
Konkreter Fall, den ich bisher aber nicht rekonstruieren konnte:
Ich war eingeloggt, ließ das eine Weile stehen und verlor die "Login-Verbindung".
D.h., ich war nur noch als Gast mit `DemoTeam` eingeloggt.

Beim Umschalten auf eine andere Seite (`Managerbüro`?) begann eine Initialisierung von 5 Tasks.
Als es nur noch 3 waren (es lief gerade die Extraktion der `Leihhistorie`), hing sich das Ganze auf.
Seitenwechsel, Klicks, etc. waren blockiert, einzig Reload (Ctrl-R o.ä.) erweckte das System wieder.

**Comment by Eselce** [comment]
Grundsätzliche Frage bleibt natürlich, ob es überhaupt synchrone Ladevorgänge sein müssen. Beides hat Vor- und Nachteile...

**Comment by Eselce** [comment]
> Verschiedene Ansätze sind hier möglich, z.B. Time-Out oder Abbruch bei Klick auf die Meldung...

Beispiel für den ersten Ansatz:

kompakter:
```
const newPromise = ((executor, millisecs = 15000) => new Promise((resolve, reject) => {
            const timerID = window.setTimeout((() => reject(Error("Timed out"))), millisecs);
            return executor((value => (window.clearTimeout(timerID), resolve(value))), reject);
        }));
```
lesbarer:
```
function getTimedPromise(executor, millisecs = 15000) {
    return new Promise((resolve, reject) => {
            const timeoutFun = (() => {
                    return reject(Error("Timed out"));
                });
            const timerID = window.setTimeout(timeoutFun, millisecs);
            const resolveFun = (value => {
                    window.clearTimeout(timerID);
                    return resolve(value);
                });
            return executor(resolveFun, reject);
        });
}
```

**Comment by rombau** [comment]
> Konkreter Fall, den ich bisher aber nicht rekonstruieren konnte: Ich war eingeloggt, ließ das eine Weile stehen und verlor die "Login-Verbindung". D.h., ich war nur noch als Gast mit `DemoTeam` eingeloggt.
> 
> Beim Umschalten auf eine andere Seite (`Managerbüro`?) begann eine Initialisierung von 5 Tasks. Als es nur noch 3 waren (es lief gerade die Extraktion der `Leihhistorie`), hing sich das Ganze auf. Seitenwechsel, Klicks, etc. waren blockiert, einzig Reload (Ctrl-R o.ä.) erweckte das System wieder.

Das konnte ich mal reproduzieren. Da gibt es 2 Probleme, die das verursachen:
1. Vor der Korrektur der Anmeldungsprüfung wurde auch die Mannschaftsseite des Demoteam erkannt; nun werden die Teamdaten des Demoteams eingelesen, dabei neue Spieler erkannt und dann alle Spielerseiten eingelesen. Bei den Leihdaten bleibt er dann hängen, weil dort als erstes erkannt wird, dass es keine Anmeldung gibt.
2. Fehler während des Einlesens im Hintergrund werden im `xhr.onload` (in `requestor.js`) "geschluckt", und nicht weiter verarbeitet. Somit kommt die Verarbeitung nie zu einem Punkt, an dem das Overlay-DIV wieder entfernt wird, und die Seiten (nicht der Browser) bleiben blockiert.

**Comment by Eselce** [comment]
War etwas ungenau ausgedrückt: Natürlich bleibt nicht der Browser blockiert, sondern die Seitenanzeige. Sorry!
Ansonsten klingt das alles sehr plausibel...
