### ISSUE TITLE
Stadioneinnahmen bei Nicht-50/50-FSS

### ISSUE THREAD

**Issue by Eselce** [rombau/osext2#26]
[quote='Oliver Schitthelm2',['index.php?page=Thread&postID=1244408#post1244408'](https://os.ongapo.com/forum/index.php?page=Thread&postID=1244408#post1244408)]

FSS werden generell als 50/50 gerechnet. Bei FSS mit anderer Verteilung stimmt die Berechnung leider nicht.

**Comment by Eselce** [comment]
Vermutliche Ursache: Nichterkennen des `FSS`-Spieltypus wegen paralleler Anwendung des `OS2.spielplan` GM-Skriptes, das zuvor läuft...

**Comment by Eselce** [comment]
Kleiner Realitätscheck: Die Erweiterung bekommt den Originaltext "zu fressen". Also z.B. `<td class=\"OMI\">Friendly : Auswärts</td>`

**Comment by rombau** [comment]
In `copyScheduledMatchDay` (Basis für die Einnahmenberechnung) wird der `friendlyShare` nicht kopiert.

**Comment by rombau** [comment]
behoben mit https://github.com/rombau/osext2/commit/32e84a28c63b59e4843002d69a868eaf6a70c5ef

hat nicht direkt mit #9 zu tun; das Problem mit den Abkürzungen im Spielplan wird dann dort behoben.

**Comment by Eselce** [comment]
Spielt jetzt keine Rolle mehr, aber meine Erkenntnis von gestern abend war, daß `matchday.friendlyShare` aus der Spielplanansicht irgendwo auf dem Weg nach `MatchDay.calculateMatchDayIncome` verlorengeht (`balancedMatchDay.calculateMatchDayIncome` in `Team.getMatchDaysWithBalance`). Dank des PRs muß ich nicht mehr danach suchen, wo das passiert... ;-)

**Comment by Eselce** [comment]
P.S.: Ich vermute, Entscheidungsspiele werden überhaupt nicht erkannt. Wie sollten die überhaupt angemessen bewertet werden, mit 50% ? Mir fehlen derzeit auch Beispiele im eigenen Spielplan, um das zu bewerten...
