### ISSUE TITLE
Unerwünschte Nebeneffekte bei Aktivierung/Deaktivierung der Erweiterung

### ISSUE THREAD

**Issue by Eselce** [rombau/osext2#28]
Immer wieder stoße ich auf merkwürdige Effekte, wenn ich die Aktivität des `AddOns` wechsle (an/aus). Beim Einschalten scheint mir ab und zu doch immer noch Initialisierung zu fehlen (sorry für diese ungenaue Angabe), beim Ausschalten gibt es Phänomene, wie z.B. daß die Tooltips auf der Spielplanseite auf einmal in Volltext auf der Seite angezeigt werden. Nun ist das kein "Tagesgeschäft" der Erweiterung, aber auf lange Sicht sollte hier vielleicht stabilisiert werden. Derzeit entlade ich zunächst die Seite, bevor ich das `AddOn` deaktiviere und ggfs. wieder aktiviere...

**Comment by rombau** [comment]
Firefox entfernt nach dem Entfernen eines Addons alle Scripts/Stylesheets, aber nicht den schon veränderten HTML-Content. Auch beim Laden des Addons werden die Scripts hinzugefügt und ausgeführt. Chrome macht das übrigens nicht.

Beim automatischen Laden wird schon geprüft, ob das HTML bereits durch die Erweiterung (osext-marker) verändert wurde; dann wird nämlich ein reload der Seite ausgelöst, da sonst z.B. die Tabellen-Prüfung fehlschlagen würde.

Beim Entfernen müsste das `chrome.management.onUninstalled` event verarbeitet werden. Dafür bräuchte die Erweiterung ein Background Script (Manifest V2) und später einen Service Worker (Manifest V3).

**Comment by rombau** [comment]
Mögliche Logik in background.js:
management.onEnabled (and onDisabled, onInstalled, onUninstalled)
=> tabs.query(management.getSelf().hostPermissions)
=> tabs.reload()

https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/manifest.json/background#browser_support
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/management
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs

**Comment by rombau** [comment]
> Mögliche Logik in background.js: management.onEnabled (and onDisabled, onInstalled, onUninstalled) 
> => tabs.query(url:management.getSelf().hostPermissions) 
> => tabs.reload()
funktioniert nicht - onDisabled wird nicht getriggert für die aktuelle Extension

**Comment by rombau** [comment]
Da es (derzeit) keine Möglichkeit gibt, auf das Deaktivieren der Erweiterung zu reagieren, wird nur das unschöne Phänomen mit übriggebliebenem DOM behoben. Dies betrifft allerdings nur Firefox; Chrome/Chromium und Edge belassen das DOM beim Aktivieren bzw Deaktivieren unverändert.
