### ISSUE TITLE
Selten auftretenes Anzeigeproblem

### ISSUE THREAD

**Issue by Eselce** [rombau/osext2#35]
[quote='Thomas Schaaf','[index.php?page=Thread&postID=1247293#post1247293](https://os.ongapo.com/forum/index.php?page=Thread&postID=1247293#post1247293)']

Ich habe manchmal ein Problem mit der Extension:
Dann erscheint bei Opti, Skill-schnitt und den anderen Feldern in der Teamübersicht nichts mehr, auch im Saisonplan nicht.

Greasemonkey habe ich abgeschaltet. Nutze die aktuelle Firefoxversion.

Immer ist das wie gesagt nicht, aber ich weiß nicht, woran es liegt. Hat wer einen Tipp?

**Comment by rombau** [comment]
Mit der aktuellen Version tritt das Problem nicht mehr auf.
