### ISSUE TITLE
Parallel-Betrieb mit GM-Scripts

### ISSUE THREAD

**Issue by rombau** [rombau/osext2#9]
Vielleicht gibt es auch eine Möglichkeit, die Scripts statt in Grease/Tampermonkey in der Extension einzubinden?

**Comment by rombau** [comment]
Die Scripts dürften direkt in die Seite "injiziert" werden (in der Konsole wird als Quelle z.b. showteam.php angegeben) und werden vor den Content Scripts der Erweiterung ausgeführt. Somit kommt es zu Problemen, wenn die Erweiterung ein bestimmtes Layout voraus setzt. 

Die Erweiterung sollte prüfen, ob Layout-Änderungen durch die GM-Scripts vorgenommen wurden (z.B. der Optionen-Button hinzugefügt wurde).

**Comment by rombau** [comment]
In den GM-Scripts gibt es kein `@run-at`, somit laufen die Scripts mit `document-end`. Die Extension Scripts laufen `run_at "document_idle" `, also nach den GM-Scripts.

**Comment by Eselce** [comment]
Somit haben sie dasselbe Problem wie konkurrierende GM-Scripts...

**Comment by Eselce** [comment]
[quote='Michael Bartz',['index.php?page=Thread&postID=1243605#post1243605'](https://os.ongapo.com/forum/index.php?page=Thread&postID=1243605#post1243605)]

Kein direkter Konflikt, aber eine Unschönheit wegen Doppelung in der Anzeige:

> `#` 	Name 	Alter	Geb.		Land 	U 	SCH 	BAK 	KOB 	ZWK 	DEC 	GES 	FUQ 	ERF 	AGG 	PAS 	AUS 	UEB 	WID 	SEL 	DIS 	ZUV 	EIN 	FixVals	Prios	**Skill	Opti**	tr.	Talent	**_Skillschn.	Opt.Skill_**


**Skript**
**_Extension_**

**Comment by Eselce** [comment]
[quote='Sven Loges',['index.php?page=Thread&postID=1243606#post1243606'](https://os.ongapo.com/forum/index.php?page=Thread&postID=1243606#post1243606)]

Danke Dir! Da fällt mir gleich noch _**ØP**_ (_**Extension**_) vs. **Prios** (**Skript**) ein.

Ich stelle mir da derzeit vor, daß die doppelte Anzeige einfach erkannt und weggelassen wird...
Also kooperativ! Ich versuche das mal im Detail zu klären, wer da auf wen achten muß...

**Comment by rombau** [comment]
möglicherweise auch ein Problem im Parallel-Betrieb: #26

**Comment by rombau** [comment]
> möglicherweise auch ein Problem im Parallel-Betrieb: #26

Bei Verwendung der "Abkürzungen" im Skript kann die Spielart (z.B. "FSS (H)" statt "Friendly : Auswärts") nicht mehr korrekt initialisiert werden. Hat aber nichts mit #26 zu tun.

**Comment by rombau** [comment]
die Ziehwarnung aus dem Skript darf von der Erweiterung nicht (mit den anderen unnötigen "Hilfezeilen") gelöscht werden

**Comment by rombau** [comment]
Das Löschen der Ziehwarnung wird (u.a.) mit https://github.com/rombau/osext2/commit/747541c70b43ceac88e7a4d767c843cb884e5f86 verhindert.

**Comment by rombau** [comment]
Alle aktuell bekannten Probleme wurden mit #34 gelöst. Sollten noch Fehler auftreten, werden diese mit eigenen Issues behoben.
